version: 2.1

jobs:
  lint-frontend-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull hadolint/hadolint
      - run: docker run --rm -i hadolint/hadolint < karsajobs-ui/Dockerfile

  lint-backend-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull hadolint/hadolint
      - run: docker run --rm -i hadolint/hadolint < Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t risqikhoirul/karsajobs-ui:latest ./karsajobs-ui
      - run: docker tag risqikhoirul/karsajobs-ui:latest ghcr.io/risqikhoirul/karsajobs-ui:latest
      - run: echo $GITHUB_TOKEN | docker login ghcr.io -u lionelritchie29 --password-stdin
      - run: docker push ghcr.io/risqikhoirul/karsajobs-ui:latest

  test-app:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t risqikhoirul/karsajobs:latest ./karsajobs
      - run: docker tag risqikhoirul/karsajobs:latest ghcr.io/risqikhoirul/karsajobs:latest
      - run: echo $GITHUB_TOKEN | docker login ghcr.io -u lionelritchie29 --password-stdin
      - run: docker push ghcr.io/risqikhoirul/karsajobs:latest

workflows:
  frontend-workflows:
    jobs:
      - lint-frontend-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-frontend-dockerfile

  backend-workflows:
    jobs:
      - lint-backend-dockerfile
      - test-app:
          requires:
            - lint-backend-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
