version: 2.1

jobs:
  lint-backend-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull hadolint/hadolint
      - run: docker run --rm -i hadolint/hadolint < Dockerfile

  test-app:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t risqikhoirul/karsajobs:latest .
      - run: docker tag risqikhoirul/karsajobs:latest ghcr.io/risqikhoirul/karsajobs:latest
      - run: echo $GITHUB_TOKEN | docker login ghcr.io -u risqikhoirul --password-stdin
      - run: docker push ghcr.io/risqikhoirul/karsajobs:latest

workflows:
  backend-workflows:
    jobs:
      - lint-backend-dockerfile
      - test-app:
          requires:
            - lint-backend-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
